In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB,BernoulliNB,MultinomialNB,CategoricalNB
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC


import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [7]:
df1 = pd.read_csv("gender_submission.csv")
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

In [3]:
df1.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [60]:
y_test = df1['Survived']

In [11]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# Data Preprocessing

In [14]:
train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [17]:
train_df.duplicated().sum()

np.int64(0)

In [16]:
test_df.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [18]:
test_df.duplicated().sum()

np.int64(0)

In [19]:
train_df_new = train_df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [20]:
train_df_new.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [21]:
test_df_new = test_df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [22]:
test_df_new

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [23]:
train_df_new.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [24]:
train_df_new['Age'].fillna(train_df_new['Age'].mean(), inplace=True)

C:\Users\ABDULLAH AL MASUM\AppData\Local\Temp\ipykernel_10672\2013542616.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df_new['Age'].fillna(train_df_new['Age'].mean(), inplace=True)

In [31]:
train_df_new.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [26]:
test_df_new.isna().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [27]:
test_df_new['Age'].fillna(test_df_new['Age'].mean(), inplace=True)

C:\Users\ABDULLAH AL MASUM\AppData\Local\Temp\ipykernel_10672\2771666658.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_df_new['Age'].fillna(test_df_new['Age'].mean(), inplace=True)

In [29]:
test_df_new['Fare'].fillna(test_df_new['Fare'].mean(), inplace=True)

C:\Users\ABDULLAH AL MASUM\AppData\Local\Temp\ipykernel_10672\3375746825.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_df_new['Fare'].fillna(test_df_new['Fare'].mean(), inplace=True)

In [30]:
test_df_new.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [51]:
train_df.shape

(891, 12)

In [52]:
test_df_new.shape

(418, 7)

# Data SPlit

In [ ]:
x_train = train_df_new.drop(['Survived'], axis=1)

In [53]:
y_train = train_df_new['Survived']

In [36]:
x_train.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [37]:
label = LabelEncoder()
std = StandardScaler()

In [38]:
x_train['Sex'] = label.fit_transform(x_train['Sex'])
test_df_new['Sex'] = label.transform(test_df_new['Sex'])

In [39]:
x_train['Embarked'] = label.fit_transform(x_train['Embarked'])
test_df_new['Embarked'] = label.transform(test_df_new['Embarked'])

In [40]:
x_train.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2

In [42]:
x_train = std.fit_transform(x_train)
test_df_new = std.transform(test_df_new)

In [50]:
x_train

array([[ 0.82737724,  0.73769513, -0.5924806 , ..., -0.47367361,
        -0.50244517,  0.58111394],
       [-1.56610693, -1.35557354,  0.63878901, ..., -0.47367361,
         0.78684529, -1.93846038],
       [ 0.82737724, -1.35557354, -0.2846632 , ..., -0.47367361,
        -0.48885426,  0.58111394],
       ...,
       [ 0.82737724, -1.35557354,  0.        , ...,  2.00893337,
        -0.17626324,  0.58111394],
       [-1.56610693,  0.73769513, -0.2846632 , ..., -0.47367361,
        -0.04438104, -1.93846038],
       [ 0.82737724,  0.73769513,  0.17706291, ..., -0.47367361,
        -0.49237783, -0.67867322]], shape=(891, 7))

In [45]:
test_df_new

array([[ 0.82737724,  0.73769513,  0.36944878, ..., -0.47367361,
        -0.49078316, -0.67867322],
       [ 0.82737724, -1.35557354,  1.33137817, ..., -0.47367361,
        -0.50747884,  0.58111394],
       [-0.36936484,  0.73769513,  2.48569343, ..., -0.47367361,
        -0.45336687, -0.67867322],
       ...,
       [ 0.82737724,  0.73769513,  0.67726619, ..., -0.47367361,
        -0.50244517,  0.58111394],
       [ 0.82737724,  0.73769513,  0.04413122, ..., -0.47367361,
        -0.48633742,  0.58111394],
       [ 0.82737724,  0.73769513,  0.04413122, ...,  0.76762988,
        -0.19824428, -1.93846038]], shape=(418, 7))

# Model Train

In [ ]:
logReg = LogisticRegression()
Knn = KNeighborsClassifier()
tree = DecisionTreeClassifier()
nai_buy1 = GaussianNB()
nai_buy2 = MultinomialNB()
nai_buy3 = BernoulliNB()
nai_buy4 = CategoricalNB()
xgb = XGBClassifier()
adaB = AdaBoostClassifier()
gb = GradientBoostingClassifier()

In [73]:
svc = SVC()

In [56]:
model_logReg = logReg.fit(x_train, y_train)
model_knn = Knn.fit(x_train, y_train)
model_tree = tree.fit(x_train, y_train)
model_nai_buy1 = nai_buy1.fit(x_train, y_train)
# model_nai_buy2 = nai_buy2.fit(x_train, y_train)
model_nai_buy3 = nai_buy3.fit(x_train, y_train)
# model_nai_buy4 = nai_buy4.fit(x_train, y_train)
model_xgb = xgb.fit(x_train, y_train)
model_adab = adaB.fit(x_train, y_train)
model_gb = gb.fit(x_train, y_train)

In [74]:
model_svc = svc.fit(x_train, y_train)

In [75]:
print("model_logReg score : ", model_logReg.score(x_train, y_train))
print("model_knn score : ", model_knn.score(x_train, y_train))
print("model_tree score : ", model_tree.score(x_train, y_train))
print("model_nai_buy1 score : ", model_nai_buy1.score(x_train, y_train))
print("model_nai_buy3 score : ", model_nai_buy3.score(x_train, y_train))
print("model_xgb score : ", model_xgb.score(x_train, y_train))
print("model_adab score : ", model_adab.score(x_train, y_train))
print("model_gb score : ", model_gb.score(x_train, y_train))
print("model_svc score : ", model_svc.score(x_train, y_train))

model_logReg score :  0.8013468013468014
model_knn score :  0.8574635241301908
model_tree score :  0.9820426487093153
model_nai_buy1 score :  0.792368125701459
model_nai_buy3 score :  0.7710437710437711
model_xgb score :  0.9640852974186308
model_adab score :  0.819304152637486
model_gb score :  0.8933782267115601
model_svc score :  0.8395061728395061

In [59]:
model_logReg_prediction = model_logReg.predict(test_df_new)
model_knn_prediction = model_knn.predict(test_df_new)
model_tree_prediction = model_tree.predict(test_df_new)
model_nai_buy1_prediction = model_nai_buy1.predict(test_df_new)
# model_nai_buy2 = nai_buy2.fit(x_train, y_train)
model_nai_buy3_prediction = model_nai_buy3.predict(test_df_new)
# model_nai_buy4 = nai_buy4.fit(x_train, y_train)
model_xgb_prediction = model_xgb.predict(test_df_new)
model_adab_prediction = model_adab.predict(test_df_new)
model_gb_prediction = model_gb.predict(test_df_new)

In [76]:
model_svc_prediction = model_svc.predict(test_df_new)

In [77]:
print("Accuracy logistic : ", accuracy_score(model_logReg_prediction, y_test))
print("Accuracy Knn : ", accuracy_score(model_knn_prediction, y_test))
print("Accuracy tree : ", accuracy_score(model_tree_prediction, y_test))
print("Accuracy Naive1 : ", accuracy_score(model_nai_buy1_prediction, y_test))
print("Accuracy Naive3 : ", accuracy_score(model_nai_buy3_prediction, y_test))
print("Accuracy GXBoost : ", accuracy_score(model_xgb_prediction, y_test))
print("Accuracy AdaBoost : ", accuracy_score(model_adab_prediction, y_test))
print("Accuracy GradientBoost : ", accuracy_score(model_gb_prediction, y_test))
print("Accuracy SVC : ", accuracy_score(model_svc_prediction, y_test))

Accuracy logistic :  0.9473684210526315
Accuracy Knn :  0.8588516746411483
Accuracy tree :  0.777511961722488
Accuracy Naive1 :  0.8971291866028708
Accuracy Naive3 :  0.8899521531100478
Accuracy GXBoost :  0.8181818181818182
Accuracy AdaBoost :  0.9617224880382775
Accuracy GradientBoost :  0.8899521531100478
Accuracy SVC :  0.930622009569378

# deep learning model

In [63]:
model_deep = Sequential()

model_deep.add(Dense(128, activation='relu', input_dim = 7))
model_deep.add(Dense(128, activation='relu'))
model_deep.add(Dense(1, activation='relu'))

c:\Users\ABDULLAH AL MASUM\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [64]:
model_deep.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,665 (69.00 KB)

 Trainable params: 17,665 (69.00 KB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model_deep.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [66]:
histroy = model_deep.fit(x_train, y_train, batch_size=30, epochs=100, verbose=1, validation_split=.2)

Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.6419 - loss: 2.0678 - val_accuracy: 0.8045 - val_loss: 0.6780
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7360 - loss: 0.9117 - val_accuracy: 0.8101 - val_loss: 1.1472
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7374 - loss: 1.2647 - val_accuracy: 0.8101 - val_loss: 1.0700
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7711 - loss: 0.7782 - val_accuracy: 0.8436 - val_loss: 0.4434
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7963 - loss: 0.5979 - val_accuracy: 0.8492 - val_loss: 0.3746
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8020 - loss: 0.5761 - val_accuracy: 0.8436 - val_loss: 0.3678
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8034 - loss: 0.5630 - val_accuracy: 0.8659 - val_loss: 0.3609
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8090 - loss: 0.5526 - val_accuracy: 0.8715 - val_loss: 0.3503
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8090 - loss: 0.5465 - val_accuracy: 0.8771 - val_loss: 0.3442
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.5423 - val_accuracy: 0.8771 - val_loss: 0.3471
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8132 - loss: 0.5398 - val_accuracy: 0.8771 - val_loss: 0.3426
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.5187 - val_accuracy: 0.8771 - val_loss: 0.3438
Epoch 13/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8076 - loss: 0.5127 - val_accuracy: 0.8156 - val_loss: 0.5118
Epoch 14/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7570 - loss: 0.8063 - val_accuracy: 0.8045 - val_loss: 0.6686
Epoch 15/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7921 - loss: 0.6546 - val_accuracy: 0.8212 - val_loss: 0.5268
Epoch 16/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8076 - loss: 0.5322 - val_accuracy: 0.8492 - val_loss: 0.4436
Epoch 17/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8020 - loss: 0.5174 - val_accuracy: 0.8603 - val_loss: 0.4303
Epoch 18/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8118 - loss: 0.5105 - val_accuracy: 0.8715 - val_loss: 0.4181
Epoch 19/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8244 - loss: 0.4862 - val_accuracy: 0.8771 - val_loss: 0.3382
Epoch 20/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8188 - loss: 0.4626 - val_accuracy: 0.8492 - val_loss: 0.3510
Epoch 21/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8174 - loss: 0.4497 - val_accuracy: 0.8659 - val_loss: 0.3677
Epoch 22/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8118 - loss: 0.4419 - val_accuracy: 0.8659 - val_loss: 0.3509
Epoch 23/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8230 - loss: 0.4331 - val_accuracy: 0.8659 - val_loss: 0.3410
Epoch 24/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8202 - loss: 0.4273 - val_accuracy: 0.8715 - val_loss: 0.3379
Epoch 25/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8230 - loss: 0.4247 - val_accuracy: 0.8715 - val_loss: 0.3384
Epoch 26/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8244 - loss: 0.4241 - val_accuracy: 0.8771 - val_loss: 0.3302
Epoch 27/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8301 - loss: 0.4212 - val_accuracy: 0.8771 - val_loss: 0.3383
Epoch 28/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8301 - loss: 0.4194 - val_accuracy: 0.8827 - val_loss: 0.3330
Epoch 29/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8287 - loss: 0.4183 - val_accuracy: 0.8827 - val_loss: 0.3321
Epoch 30/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8258 - loss: 0.4170 - val_accuracy: 0.8827 - val_loss: 0.3304
Epoch 31/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8244 - loss: 0.4184 - val_accuracy: 0.8771 - val_loss: 0.3464
Epoch 32/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8315 - loss: 0.4139 - val_accuracy: 0.8827 - val_loss: 0.3242
Epoch 33/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8357 - loss: 0.4138 - val_accuracy: 0.8771 - val_loss: 0.3289
Epoch 34/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8343 - loss: 0.4138 - val_accuracy: 0.8715 - val_loss: 0.3379
Epoch 35/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8357 - loss: 0.4117 - val_accuracy: 0.8771 - val_loss: 0.3263
Epoch 36/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8343 - loss: 0.4106 - val_accuracy: 0.8715 - val_loss: 0.3324
Epoch 37/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8357 - loss: 0.4097 - val_accuracy: 0.8715 - val_loss: 0.3312
Epoch 38/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8343 - loss: 0.4089 - val_accuracy: 0.8771 - val_loss: 0.3251
Epoch 39/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8357 - loss: 0.4090 - val_accuracy: 0.8659 - val_loss: 0.3335
Epoch 40/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8357 - loss: 0.4101 - val_accuracy: 0.8827 - val_loss: 0.3257
Epoch 41/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8301 - loss: 0.4077 - val_accuracy: 0.8603 - val_loss: 0.4014
Epoch 42/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8343 - loss: 0.4054 - val_accuracy: 0.8771 - val_loss: 0.3375
Epoch 43/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8413 - loss: 0.4040 - val_accuracy: 0.8771 - val_loss: 0.3342
Epoch 44/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8385 - loss: 0.4027 - val_accuracy: 0.8715 - val_loss: 0.3332
Epoch 45/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8385 - loss: 0.4037 - val_accuracy: 0.8771 - val_loss: 0.3273
Epoch 46/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8343 - loss: 0.4029 - val_accuracy: 0.8547 - val_loss: 0.4060
Epoch 47/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8399 - loss: 0.4014 - val_accuracy: 0.8771 - val_loss: 0.3333
Epoch 48/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8399 - loss: 0.4019 - val_accuracy: 0.8659 - val_loss: 0.3976
Epoch 49/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8329 - loss: 0.4002 - val_accuracy: 0.8771 - val_loss: 0.3327
Epoch 50/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8399 - loss: 0.3994 - val_accuracy: 0.8659 - val_loss: 0.4020
Epoch 51/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8371 - loss: 0.3984 - val_accuracy: 0.8715 - val_loss: 0.3320
Epoch 52/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8343 - loss: 0.3992 - val_accuracy: 0.8715 - val_loss: 0.4022
Epoch 53/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8371 - loss: 0.3974 - val_accuracy: 0.8659 - val_loss: 0.3397
Epoch 54/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8371 - loss: 0.3985 - val_accuracy: 0.8659 - val_loss: 0.4077
Epoch 55/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8441 - loss: 0.3997 - val_accuracy: 0.8715 - val_loss: 0.3226
Epoch 56/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8357 - loss: 0.3973 - val_accuracy: 0.8659 - val_loss: 0.3983
Epoch 57/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8455 - loss: 0.3948 - val_accuracy: 0.8715 - val_loss: 0.3392
Epoch 58/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8399 - loss: 0.3943 - val_accuracy: 0.8715 - val_loss: 0.4000
Epoch 59/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8399 - loss: 0.3923 - val_accuracy: 0.8659 - val_loss: 0.4006
Epoch 60/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8413 - loss: 0.3927 - val_accuracy: 0.8659 - val_loss: 0.3983
Epoch 61/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8427 - loss: 0.3925 - val_accuracy: 0.8659 - val_loss: 0.4083
Epoch 62/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8469 - loss: 0.3910 - val_accuracy: 0.8659 - val_loss: 0.3976
Epoch 63/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8497 - loss: 0.3907 - val_accuracy: 0.8603 - val_loss: 0.4055
Epoch 64/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8455 - loss: 0.3887 - val_accuracy: 0.8659 - val_loss: 0.4023
Epoch 65/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8441 - loss: 0.3910 - val_accuracy: 0.8659 - val_loss: 0.4039
Epoch 66/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8441 - loss: 0.3912 - val_accuracy: 0.8659 - val_loss: 0.3396
Epoch 67/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8413 - loss: 0.3881 - val_accuracy: 0.8603 - val_loss: 0.4741
Epoch 68/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8455 - loss: 0.3878 - val_accuracy: 0.8603 - val_loss: 0.4009
Epoch 69/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8427 - loss: 0.3877 - val_accuracy: 0.8659 - val_loss: 0.4041
Epoch 70/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8385 - loss: 0.4136 - val_accuracy: 0.8603 - val_loss: 0.4780
Epoch 71/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8441 - loss: 0.3897 - val_accuracy: 0.8547 - val_loss: 0.3329
Epoch 72/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8511 - loss: 0.3866 - val_accuracy: 0.8603 - val_loss: 0.4738
Epoch 73/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8497 - loss: 0.3836 - val_accuracy: 0.8547 - val_loss: 0.4006
Epoch 74/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8483 - loss: 0.3831 - val_accuracy: 0.8659 - val_loss: 0.4066
Epoch 75/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8469 - loss: 0.3842 - val_accuracy: 0.8659 - val_loss: 0.4038
Epoch 76/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8455 - loss: 0.3901 - val_accuracy: 0.8436 - val_loss: 0.5682
Epoch 77/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7893 - loss: 1.0151 - val_accuracy: 0.8156 - val_loss: 0.8469
Epoch 78/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8118 - loss: 0.8644 - val_accuracy: 0.8212 - val_loss: 0.7385
Epoch 79/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8202 - loss: 0.7313 - val_accuracy: 0.8324 - val_loss: 0.5919
Epoch 80/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7949 - loss: 0.8301 - val_accuracy: 0.8045 - val_loss: 1.1620
Epoch 81/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7767 - loss: 0.8446 - val_accuracy: 0.8380 - val_loss: 0.6735
Epoch 82/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8216 - loss: 0.5572 - val_accuracy: 0.8492 - val_loss: 0.4164
Epoch 83/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8357 - loss: 0.5196 - val_accuracy: 0.8380 - val_loss: 0.6859
Epoch 84/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8287 - loss: 0.4862 - val_accuracy: 0.8547 - val_loss: 0.3786
Epoch 85/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8146 - loss: 0.4486 - val_accuracy: 0.8324 - val_loss: 0.4976
Epoch 86/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8343 - loss: 0.4348 - val_accuracy: 0.8715 - val_loss: 0.3284
Epoch 87/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8315 - loss: 0.3999 - val_accuracy: 0.8492 - val_loss: 0.3396
Epoch 88/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8371 - loss: 0.3969 - val_accuracy: 0.8492 - val_loss: 0.4065
Epoch 89/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8413 - loss: 0.3975 - val_accuracy: 0.8492 - val_loss: 0.4122
Epoch 90/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8385 - loss: 0.3922 - val_accuracy: 0.8603 - val_loss: 0.3353
Epoch 91/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8371 - loss: 0.3903 - val_accuracy: 0.8547 - val_loss: 0.3317
Epoch 92/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8413 - loss: 0.3873 - val_accuracy: 0.8492 - val_loss: 0.4065
Epoch 93/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8427 - loss: 0.3860 - val_accuracy: 0.8492 - val_loss: 0.4007
Epoch 94/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3878 - val_accuracy: 0.8547 - val_loss: 0.4137
Epoch 95/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8399 - loss: 0.3871 - val_accuracy: 0.8547 - val_loss: 0.4104
Epoch 96/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8413 - loss: 0.3834 - val_accuracy: 0.8603 - val_loss: 0.4676
Epoch 97/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8343 - loss: 0.3843 - val_accuracy: 0.8492 - val_loss: 0.4023
Epoch 98/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8427 - loss: 0.3833 - val_accuracy: 0.8547 - val_loss: 0.4682
Epoch 99/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8399 - loss: 0.3795 - val_accuracy: 0.8547 - val_loss: 0.4717
Epoch 100/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8427 - loss: 0.3803 - val_accuracy: 0.8547 - val_loss: 0.4676

In [67]:
y_pred = model_deep.predict(test_df_new)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

In [69]:
y_pred = y_pred.argmax(axis=1)

In [70]:
accuracy_score(y_pred, y_test)

0.6363636363636364

# parameter Tuning

In [80]:
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'penalty': ['l2'],
    'solver': ['lbfgs'],
    'max_iter': [100, 200]
}

In [81]:
random = RandomizedSearchCV(model_logReg, param_grid, cv=5, n_iter=10)
random.fit(x_train, y_train)

c:\Users\ABDULLAH AL MASUM\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [0.01, 0.1, 1, 10],
                                        'max_iter': [100, 200],
                                        'penalty': ['l2'],
                                        'solver': ['lbfgs']})

In [84]:
y_pred = random.predict(test_df_new)

In [85]:
random.score(x_train, y_train)

0.8080808080808081

In [86]:
accuracy_score(y_pred, y_test)

0.9473684210526315

In [88]:
param_grid = {
    "n_estimators": [100, 200, 300, 500],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "max_depth": [3, 4, 5, 6, 8],
    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],
    "gamma": [0, 0.1, 0.3, 0.5],
    "reg_alpha": [0, 0.01, 0.1, 1],
    "reg_lambda": [1, 1.5, 2, 5]
}

search = RandomizedSearchCV(
    estimator=model_xgb,
    param_distributions=param_grid,
    n_iter=50,
    scoring="accuracy",   # use "f1" for imbalanced data
    cv=5,
    verbose=1,
    n_jobs=-1,
    random_state=42
)

search.fit(x_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_constrain...
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None, ...),
                   n_iter=50, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.6, 0.8, 1.0],
                                        'gamma': [0, 0.1, 0.3, 0.5],
                                        'learning_rate': [0.01, 0.05, 0.1, 0.2],
                                        'max_depth': [3, 4, 5, 6, 8],
                                        'n_estimators': [100, 200, 300, 500],
                                        'reg_alpha': [0, 0.01, 0.1, 1],
                                        'reg_lambda': [1, 1.5, 2, 5],
                                        'subsample': [0.6, 0.8, 1.0]},
                   random_state=42, scoring='accuracy', verbose=1)

In [89]:
y_pred2 = search.predict(test_df_new)

In [94]:
y_pred2

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [90]:
search.score(x_train, y_train)

0.8787878787878788

In [91]:
accuracy_score(y_pred2, y_test)

0.8875598086124402

In [100]:
test_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [99]:
df1

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [122]:
pred_df = pd.DataFrame({
  "PassengerId" : test_df['PassengerId'],
  "Survived" : y_pred2
})

In [125]:
df1.drop(['Survived'], inplace = True, axis=1)

In [127]:
final_df = pred_df.merge(df1, on="PassengerId")

In [128]:
final_df

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [129]:
final_df.to_csv("submission.csv", index=False)

In [ ]:
# ================= Logistic Regression =================
log_params = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga'],
    'max_iter': [100, 200, 500]
}

# ================= KNN =================
knn_params = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski'],
    'p': [1, 2]
}

# ================= Decision Tree =================
dt_params = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 5, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': [None, 'sqrt', 'log2']
}

# ================= AdaBoost =================
ada_params = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1],
    'algorithm': ['SAMME']
}

# ================= Gradient Boosting =================
gb_params = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.8, 1.0],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

# ================= XGBoost =================
xgb_params = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'gamma': [0, 0.1, 0.2]
}

# ================= SVM =================
svc_params = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto', 0.1, 0.01]
}

# ================= Bernoulli Naive Bayes =================
bnb_params = {
    'alpha': [0.1, 0.5, 1.0, 2.0],
    'binarize': [0.0, 0.5, 1.0],
    'fit_prior': [True, False]
}

In [ ]:
grid = GridSearchCV(
    LogisticRegression(),
    log_params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)