In [77]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [78]:
df = pd.read_csv("../Data/insurance.csv")

In [79]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [80]:
df.shape

(1338, 7)

In [81]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [82]:
df.duplicated().sum()

np.int64(1)

In [83]:
df.drop_duplicates(inplace=True)

In [84]:
df.duplicated().sum()

np.int64(0)

In [85]:
def types_count(col):
  return col.value_counts()

In [86]:
types_count(df['sex'])

sex
male      675
female    662
Name: count, dtype: int64

In [87]:
types_count(df['smoker'])

smoker
no     1063
yes     274
Name: count, dtype: int64

In [88]:
types_count(df['region'])

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

In [89]:
df['sex'] = df['sex'].map({'male' : 1, 'female' : 0})
df['smoker'] = df['smoker'].map({'yes' : 1, 'no' : 0})
df['region'] = df['region'].map({'southeast' : 0, 'southwest' : 1, 'northwest' : 2, 'northeast' : 3})

In [90]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       0   1725.55230
2   28    1  33.000         3       0       0   4449.46200
3   33    1  22.705         0       0       2  21984.47061
4   32    1  28.880         0       0       2   3866.85520

In [91]:
# def remove_outliers_iqr(df, column):
#     Q1 = df[column].quantile(0.25)
#     Q3 = df[column].quantile(0.75)
#     IQR = Q3 - Q1
    
#     lower_bound = Q1 - 1.5 * IQR
#     upper_bound = Q3 + 1.5 * IQR
    
#     # Filter the DataFrame
#     df_cleaned = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
#     return df_cleaned

In [92]:
# df = remove_outliers_iqr(df, 'charges')

In [93]:
df.shape

(1337, 7)

In [94]:
Y = df['charges']
X = df.drop('charges', axis=1)

In [95]:
X

      age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       1
1      18    1  33.770         1       0       0
2      28    1  33.000         3       0       0
3      33    1  22.705         0       0       2
4      32    1  28.880         0       0       2
...   ...  ...     ...       ...     ...     ...
1333   50    1  30.970         3       0       2
1334   18    0  31.920         0       0       3
1335   18    0  36.850         0       0       0
1336   21    0  25.800         0       0       1
1337   61    0  29.070         0       1       2

[1337 rows x 6 columns]

In [96]:
Y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1337, dtype: float64

In [97]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=42, test_size=.25)

In [98]:
x_train.shape

(1002, 6)

In [99]:
x_test.shape

(335, 6)

In [100]:
print(y_train.shape)
print(y_test.shape)

(1002,)
(335,)

In [101]:
std = StandardScaler()

In [102]:
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)

In [103]:
lr = LinearRegression()

In [104]:
model = lr.fit(x_train, y_train)

In [105]:
model.score(x_train, y_train)

0.7297179912948285

In [107]:
model.score(x_test, y_test)

0.7962585193217646

In [106]:
pre_y = model.predict(x_test)

In [108]:
mean_absolute_error(y_test, pre_y)

4063.959185760238

In [109]:
mean_squared_error(y_test, pre_y)

35228901.67560052

In [110]:
import pickle

In [111]:
with open("model.pkl", 'wb') as f:
  pickle.dump(model, f)